#!/bin/sh
#
# init devices
#

case "$1" in
  start)
 	echo "Loading network driver..."
	modprobe smsc95xx
 	echo "Loading wifi driver..."
	modprobe 8192cu
 	echo "Loading sound driver..."
	modprobe snd-bcm2835
 	#Set output to analog
	amixer cset numid=3 1
	#Resets the volume to last value
	alsactl init
	;;
  stop)
	echo -n "Unloading sound driver..."
	modprobe -r snd-bcm2835
	echo -n "Unloading wifi driver..."
	modprobe -r 8192cu
	echo -n "Unloading network driver..."
	modprobe -r smsc95xx
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

