#!/bin/sh
#
# init devices
#

case "$1" in
  start)
 	echo "Starting hostapd..."
    hostapd -B /etc/hostapd/hostapd.conf 2>/dev/null >/dev/null
	;;
  stop)
        killall hostapd 2>/dev/null
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

